"""
Music Duplicate Undo  v2.0
===========================
Reads a CSV report generated by find_music_duplicates.py and moves all
files back to their original locations in the unsorted folder.

Works with the new CSV format (v3.0 of the main script).

Usage:
    python undo_duplicates.py "C:\\Music\\Duplicates\\music_report_YYYYMMDD_HHMMSS.csv"

Options:
    --dry-run     Preview what would be restored without actually moving anything
    --filter-category CATEGORY
                  Only undo a specific category. Options:
                  "Exact Match", "Standard Duplicate", "Higher Quality Match"
"""

import sys
import csv
import shutil
from pathlib import Path
from datetime import datetime

DRY_RUN = "--dry-run" in sys.argv

# Parse --filter-category flag
_filter_flag = next(
    (sys.argv[i + 1] for i, a in enumerate(sys.argv)
     if a == "--filter-category" and i + 1 < len(sys.argv)),
    None,
)
FILTER_CATEGORY = _filter_flag


# ── Actions that represent a file that was actually moved ──────────────────
MOVED_ACTIONS = {
    "Auto-moved to Duplicates",
    "Moved to DUPLICATE",
    "Moved to BETTER QUALITY",
    # Friendly label variants
    "Moved to Duplicates",
    "Moved to Better Quality",
}

def was_moved(action: str) -> bool:
    return any(action.strip().lower().startswith(a.lower()) for a in {
        "auto-moved", "moved to"
    })


def load_csv(csv_path: Path) -> list[dict]:
    """Load all rows from the CSV report."""
    rows = []
    with open(csv_path, encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def filter_rows(rows: list[dict]) -> list[dict]:
    """Return only rows that represent files that were actually moved."""
    filtered = []
    for row in rows:
        action   = row.get("Action", "").strip()
        category = row.get("Category", "").strip()

        if not was_moved(action):
            continue
        if FILTER_CATEGORY and category.lower() != FILTER_CATEGORY.lower():
            continue
        # Skip dry-run rows (they say "Would move/auto-move")
        if "would" in action.lower():
            continue

        filtered.append(row)
    return filtered


def undo(csv_path: Path):
    if not csv_path.exists():
        print(f"ERROR: CSV file not found: {csv_path}")
        return

    print("=" * 65)
    print("Music Duplicate Undo")
    if DRY_RUN:
        print("*** DRY RUN: No files will be moved ***")
    print(f"Started  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"CSV file : {csv_path}")
    if FILTER_CATEGORY:
        print(f"Filter   : {FILTER_CATEGORY}")
    print("=" * 65)

    all_rows = load_csv(csv_path)
    rows     = filter_rows(all_rows)

    if not rows:
        print("\nNo moved files found in the CSV to undo.")
        print("(Only rows with 'Moved to' or 'Auto-moved' actions are restored.)")
        return

    print(f"\nFound {len(rows)} file(s) to restore.\n")

    restored = 0
    skipped  = 0
    errors   = 0

    for row in rows:
        category     = row.get("Category", "").strip()
        original_str = row.get("Unsorted Path", "").strip()
        current_str  = row.get("Destination Path", "").strip()

        if not original_str or not current_str:
            print(f"[SKIP]  Missing path data in row — skipping.")
            skipped += 1
            continue

        original = Path(original_str)
        current  = Path(current_str)

        print(f"[{category}]")

        if not current.exists():
            print(f"  [MISSING]  File no longer at destination:")
            print(f"             {current}")
            print(f"  Skipping.\n")
            skipped += 1
            continue

        if original.exists():
            print(f"  [SKIP]  A file already exists at the original location:")
            print(f"          {original}")
            print(f"  Skipping.\n")
            skipped += 1
            continue

        if DRY_RUN:
            print(f"  [WOULD RESTORE] {current}")
            print(f"              → {original}\n")
            restored += 1
        else:
            try:
                original.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(current), str(original))
                print(f"  [RESTORED] {current}")
                print(f"          → {original}\n")
                restored += 1
            except Exception as e:
                print(f"  [ERROR]  Could not restore {current}")
                print(f"           Reason: {e}\n")
                errors += 1

    print("=" * 65)
    print("SUMMARY")
    if DRY_RUN:
        print(f"  Files that would be restored : {restored}")
    else:
        print(f"  Files successfully restored  : {restored}")
    print(f"  Files skipped                : {skipped}")
    print(f"  Errors                       : {errors}")
    print("=" * 65)


if __name__ == "__main__":
    # Find the CSV path argument (skip flags)
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        print("Usage: python undo_duplicates.py <path_to_csv_report> [options]")
        print()
        print("Options:")
        print("  --dry-run                      Preview only, nothing moves")
        print("  --list-categories              Show categories in the CSV and exit")
        print("  --filter-category CATEGORY     Only undo files in this category")
        print()
        print("Examples:")
        print(r'  python undo_duplicates.py "C:\Music\Duplicates\music_report_20260226_120000.csv"')
        print(r'  python undo_duplicates.py "C:\Music\Duplicates\music_report_20260226_120000.csv" --dry-run')
        print(r'  python undo_duplicates.py "C:\Music\Duplicates\music_report_20260226_120000.csv" --list-categories')
        print(r'  python undo_duplicates.py "C:\Music\Duplicates\music_report_20260226_120000.csv" --filter-category "Exact Match"')
        sys.exit(1)

    csv_file = Path(args[0].strip('"'))
    undo(csv_file)
